<?php

/**
 * @file
 * Contains commerce_shipping.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_shipping_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_shipping module.
    case 'help.page.commerce_shipping':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Handles shipping and fulfilment for Drupal Commerce') . '</p>';
      return $output;

    default:
  }
}
